config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  resources :cats
  
  root 'galleries#index'
  
  

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :galleries
  before_create :generate_token
  
  
  def generate_token
    self.token = loop do
      random_token = SecureRandom.base64(12).gsub("/","a").gsub("+","b")
      break random_token unless Cat.find_by_token(random_token)
    end
  end
  
  def random_galleries(count)
    galleries.limit(count)
  end
  
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :cat
  has_many :pics
  before_create :generate_token
  paginates_per 20
  
  
  def generate_token
    self.token = loop do
      random_token = SecureRandom.base64(12).gsub("/","a").gsub("+","b")
      break random_token unless Gallery.find_by_token(random_token)
    end
  end
  
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  belongs_to :gallery
  
  before_create :generate_token
  
  paginates_per 1
  
  
  
  def generate_token
    self.token = loop do
      random_token = SecureRandom.base64(12).gsub("/","a").gsub("+","b")
      break random_token unless Pic.find_by_token(random_token)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [ :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
    @cat = Cat.find_by_token(params[:id])
    @page_title = @cat.name
    @galleries = @cat.galleries.page params[:page]
    @total_count = @cat.galleries.count
    @pages =  @cat.galleries.page(20).total_pages
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name)
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [ :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @page = (params[:page] || 1).to_i
    @gallery = Gallery.find_by_token(params[:id])
    @page_title = @gallery.name
    @cat = @gallery.cat
    @pics = @gallery.pics.page params[:page]
    @pic = @pics.first

    @total_count = @gallery.pics.count
    
    if @page < @total_count
      @next_pic = @gallery.pics[@page]
    else
      @next_pic = @gallery.pics[0]
    end
    
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :count_pic, :cat_id, :click_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/cats/show.html.erb
<div class="image">
     <div class="image_left">
         <div class="disp2">
             <div class="disp2_<%=@cat.id-1%>"></div>
                <div class="datalist">
                    <table id="DataList1" cellspacing="0" border="0" style="width:800px;border-collapse:collapse;">
                        <tr>
                        <%i=0%>

                        <%@galleries.each do |g|%>
                            <%if i%5==0 &&i!=0%>
                                </tr><tr>
                            <%end%>
	                        <td align="center" valign="top" style="width:158px;">
                                <div class="disp_img">
                                    <a id="link<%=g.token%>" href="<%=gallery_path(g.token)%>" target="_blank">
                                        <img id="img<%=g.token%>" src="<%=g.oss_url%>" alt="<%=g.name%>" style="height:190px;width:130px;border-width:0px;" />
                                    </a>
                                </div>
                            </td>
                            <%i+=1%>
                            
                        <%end%>
                        </tr>
               
                    </table>
                </div>
                <div class="fenye">
                    
                    <div id="AspNetPager1" class="pages" style="width:100%;white-space:nowrap;">
                        <div class="pages" style="width:30%;float:left;">
                        	共<%=@total_count%>条，共<%=@pages%>页，20条/每页
                        </div>
                        <%= paginate @galleries %>
                        <div style="clear:both"></div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>

</div>

app/views/galleries/index.html.erb
<%Cat.all.each do |cat|%>
    <div class="disp1">
        <div class="disp1_<%=cat.id-1%>">
            <div class="menu_left"></div>
            <div class="menu_right"><a href="<%=cat_path(cat.token)%>">更多&gt;&gt;</a></div>
        </div>
    <div>
    <table id="DataList<%=cat.id-1%>" cellspacing="0" border="0" style="width:100%;border-collapse:collapse;">
        <tr>
        
        <%cat.random_galleries(6).each do |gallery| %>
            	<td align="center" valign="top" style="width:158px;">
                    <div class="disp_img">
                      <a id="<%=gallery.token%>" href="<%=gallery_path(gallery.token)%>" target="_blank"><img id="img<%=gallery.token%>" src="<%=gallery.oss_url%>" alt="<%=gallery.name%>" style="height:190px;width:130px;border-width:0px;" /></a>
                    </div>
                    <a id="link<%=gallery.token%>" class="link" href="<%=gallery_path(gallery.token)%>" target="_blank"><span id="label<%=gallery.token%>"><%=gallery.name%> <%=gallery.pics.count%>P</span></a>
                </td>
        <%end%>
        </tr>
        
    </table>
    </div>
<%end%>

app/views/galleries/show.html.erb
<div class="title">
    <h1><span id="Labeltitle" style="color:DodgerBlue;font-size:18px;font-weight:bold;"><%=@gallery.name%> 第<%=@pic.code%>张图片</span>
    </h1>
</div>

<div style=" margin:0 auto; height:30px; width:988px"></div>
    <div class="disp_img3">
        <table align="center">
            <tr>
                <td align="center">
                    <%if @page < @total_count%>
                        <a id="HyperLink4" class="cursor" href="<%=gallery_path(id:@gallery.token,page:@page+1)%>"><img id="Image1" class="shadow" src="<%=@pic.oss_url%>" alt="<%=@gallery.name%> 第<%=@pic.code%>张图片" style="border-color:#666666;border-width:1px;border-style:Solid;width:900px;" /></a></td>
                    <%else%>
                        <img id="Image1" class="shadow" src="<%=@pic.oss_url%>" alt="<%=@gallery.name%> 第<%=@pic.code%>张图片" style="border-color:#666666;border-width:1px;border-style:Solid;width:900px;" />
                    <%end%>
            </tr>
        </table></div> 
        <div class="bottom_nav">
            <table id="DataList1" cellspacing="0" align="Center" border="0" style="border-collapse:collapse;">
            	<tr>
                    <%page=0%>
                    <%@gallery.pics.each do |pic|%>
                        <%page+=1%>
                		<td>
                            <a href='<%=gallery_path(id:@gallery.token,page:page)%>' ><%=page%></a>
                        </td>
                    <%end%>
            	</tr>
            </table>
        </div>
    </div>
</div>

<script>
    var img = new Image();//实例化一个图片的对象 
    img.src = "<%=@next_pic.oss_url%>"; 
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link href="/css/mycss.css" rel="stylesheet" type="text/css" />
  <title>><%= @page_title ? "#{@page_title.to_s} - 宅男福利社" :  '美女图库 美女图片 美女套图 - 宅男福利社'%></title>    
  <meta name="keywords" content="<%= @page_title ? "#{@page_title.to_s} - 宅男福利社" :  '美女图库 美女图片 美女套图 - 宅男福利社'%>" />
  <meta name="description" content="<%= @page_title ? "#{@page_title.to_s} - 宅男福利社" :  '美女图库 美女图片 美女套图 - 宅男福利社'%>"
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <%= csrf_meta_tags %>
</head>
<body>
    <%if not @cat%>
        <div class="menu">
            <%=link_to "美女图库","/",:class=>"cur"%>
            <%Cat.all.each do |cat|%>
                <%=link_to cat.name,cat_path(cat.token) %>
            <%end%>
        </div>
    <%else%>
        <div class="menu">
            <%=link_to "美女图库","/"%>
            <%Cat.all.each do |cat|%>
                <%if cat == @cat%>
                    <%=link_to cat.name,cat_path(cat.token),:class=>"cur" %>
                <%else%>
                    <%=link_to cat.name,cat_path(cat.token) %>
                <%end%>
            <%end%>
        </div>
    <%end%>
    
<div class="ad_top">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- header -->
<ins class="adsbygoogle"
     style="display:inline-block;width:970px;height:90px"
     data-ad-client="ca-pub-4598677338433468"
     data-ad-slot="7792082895"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

<%= yield %>
<!-- <div class="friend">--友情链接--<br />
</div> -->
<div class="bottom">Copyright © 2017 All rights reserved<br />
免责声明：本站提供的图片仅做为交流与欣赏，请勿用于商业活动。
<a target=blank href="mailto:youshengxiao@qq.com">点击这里给我发消息</a><br />
本站提供的图片均来自互联网，如无意中侵犯到您的权益，请与我们联系，我们会尽快清除相关内容。</div>
</body>
</html>